### ISSUE TITLE
Final Release Checklist

### ISSUE THREAD

**Issue by pskrbasu** [turbot/powerpipe#42]
- [ ] Private --> Public repo
- [ ] Update installer to remove API code (after repo goes public)
- [ ] Update installer to use sh shebang instead of bash (after repo goes public)
- [ ] Update Dockerfile to remove the GITHUB_TOKEN parts (after repo goes public)
- [ ] Release workflow including homebrew/github registry publishing
- [ ] Add the powerpipe specific script in homebrew-tap for versioning
- [ ] Remove existing pre-releases
- [ ] Should we pack the README and CHANGELOG in the released tar.gz like Flowpipe? Or just the binary like Steampipe?
- [ ] Update pipe fittings with powerpipe specific stuff:
- [ ] Merge local `pp-workspace-sample` pipe-fittings branch to get the sample workspaces file
- [ ] Make the corresponding powerpipe changes after merging the pipe-fittings branch
- [ ]
